// Curated from the owner's supplied catalog brief. No unverified numeric specs.
export const pending =
  "Contact us for the specification of your selected model.";
export const categories = [
  {
    id: "battery-materials",
    name: "Battery materials",
    description:
      "Hard carbon, porous carbon, CVD silicon–carbon and NFPP powders for electrode research.",
  },
  {
    id: "binders-electrolytes",
    name: "Binders & electrolytes",
    description:
      "Model-specific binders and electrolytes for battery development.",
  },
  {
    id: "electrodes-cells",
    name: "Electrodes & cells",
    description:
      "NFPP and P2 electrodes, research pouch cells and prismatic cells.",
  },
  {
    id: "lab-supplies",
    name: "Lab supplies & equipment",
    description:
      "Filtration media, reactor glassware, accessories and electrochemical equipment.",
  },
];
const powderFields = [
  "Grade",
  "Feedstock type",
  "Particle size",
  "BET surface area",
  "Pore volume",
  "Specific capacity",
  "Initial coulombic efficiency",
  "Test conditions",
  "Packaging",
];
const p = (
  id,
  category,
  name,
  description,
  models,
  specs,
  fields,
  note = "",
) => ({
  id,
  category,
  name,
  description,
  models,
  specs: Object.fromEntries(fields.map((key) => [key, specs[key] || pending])),
  note,
});
export const products = [
  p(
    "sodium-hard-carbon",
    "battery-materials",
    "Hard carbon for sodium-ion batteries",
    "Biomass-derived and resin-derived hard carbon for sodium-ion anode development.",
    ["Biomass-derived — grade to confirm", "Resin-derived — grade to confirm"],
    {
      "Feedstock type":
        "Biomass-derived or resin-derived; confirm the selected grade.",
    },
    powderFields,
  ),
  p(
    "spherical-porous-carbon",
    "battery-materials",
    "Spherical porous carbon",
    "Porous carbon for silicon–carbon anode research and as a host for silicon deposition.",
    [
      "Alkali-activated — grade to confirm",
      "Water-activated — grade to confirm",
    ],
    {
      "Activation type":
        "Alkali-activated or water-activated; route and grade to be confirmed.",
    },
    [...powderFields, "Activation type"],
  ),
  p(
    "cvd-silicon-carbon",
    "battery-materials",
    "CVD silicon–carbon anode powder",
    "Silicon–carbon powder for anode research, including spherical material with a secondary carbon coating.",
    ["Spherical, secondary carbon coating — grade to confirm"],
    {
      "Morphology / coating":
        "Spherical; secondary carbon coating. Confirm against the selected grade specification.",
    },
    [...powderFields, "Morphology / coating"],
  ),
  p(
    "nfpp-powder",
    "battery-materials",
    "NFPP cathode powder",
    "NFPP powder for sodium-ion research and electrode processing, including a rate-oriented material option.",
    ["NFPP — grade to confirm", "Rate-oriented NFPP — grade to confirm"],
    {},
    powderFields,
    "Rate capability depends on the selected grade and agreed test conditions; no performance value is specified.",
  ),
  p(
    "al-3001a",
    "binders-electrolytes",
    "A&L AL-3001A SBR binder",
    "SBR binder for negative-electrode development.",
    ["AL-3001A"],
    {
      Model: "AL-3001A",
      "Supplier designation": "A&L",
      Application: "Negative-electrode binder",
    },
    [
      "Model",
      "Supplier designation",
      "Application",
      "Solids content",
      "Packaging",
      "Storage conditions",
    ],
  ),
  p(
    "jone-174",
    "binders-electrolytes",
    "JONE-174 battery binder",
    "Battery binder identified by the supplied model code. Formal product naming and compatible chemistries require specification confirmation.",
    ["JONE-174"],
    { Model: "JONE-174" },
    [
      "Model",
      "Formal product name",
      "Compatible chemistry",
      "Solids content",
      "Packaging",
      "Storage conditions",
    ],
  ),
  ...["QMS029D", "XYSS-DGHYKJ118"].map((model) =>
    p(
      model.toLowerCase(),
      "binders-electrolytes",
      `${model} electrolyte`,
      "Battery research electrolyte supplied by model. Confirm chemistry compatibility and the model specification before selection.",
      [model],
      { Model: model },
      [
        "Model",
        "Compatible chemistry",
        "Composition",
        "Voltage limit",
        "Packaging",
        "Storage conditions",
      ],
    ),
  ),
  p(
    "nfm-electrolyte",
    "binders-electrolytes",
    "Electrolyte for NFM sodium-ion systems",
    "Electrolyte selection for NFM sodium-ion development. The exact model remains to be confirmed.",
    ["NFM-compatible — model to confirm"],
    { Application: "NFM sodium-ion development; compatibility to confirm." },
    [
      "Model",
      "Application",
      "Composition",
      "Voltage limit",
      "Packaging",
      "Storage conditions",
    ],
  ),
  p(
    "nfpp-electrode",
    "electrodes-cells",
    "NFPP cathode electrodes",
    "NFPP cathode electrodes for sodium-ion experiments. Coating configuration and dimensions are confirmed for each model.",
    ["Single-sided — model to confirm", "Double-sided — model to confirm"],
    { "Active material": "NFPP" },
    [
      "Model",
      "Active material",
      "Coating sides",
      "Dimensions",
      "Areal capacity (mAh/cm²)",
      "Mass loading (mg/cm²)",
      "Current collector",
      "Packaging",
    ],
  ),
  p(
    "p2-electrode",
    "electrodes-cells",
    "P2 sodium-ion cathode electrodes",
    "P2 cathode electrodes for sodium-ion research, including a double-sided cut-sheet option.",
    ["7.5 × 5.4 cm, double-sided"],
    { Dimensions: "7.5 × 5.4 cm", "Coating sides": "Double-sided" },
    [
      "Model",
      "Dimensions",
      "Coating sides",
      "Areal capacity (mAh/cm²)",
      "Mass loading (mg/cm²)",
      "Current collector",
      "Packaging",
    ],
    "Confirm loading and capacity data for the selected model, including whether values refer to one side or both sides. Areal capacity and mass loading are separate quantities.",
  ),
  p(
    "research-pouch-cells",
    "electrodes-cells",
    "Research pouch cells",
    "Existing sodium-ion and lithium-ion platforms for R&D. Select dry cells or electrolyte-filled, formed cells; platform suitability is reviewed with your requirements.",
    [
      "Sodium-ion — dry cell",
      "Sodium-ion — filled and formed",
      "Lithium-ion — dry cell",
      "Lithium-ion — filled and formed",
    ],
    {},
    [
      "Platform / model",
      "Electrode chemistry",
      "Delivery state",
      "Nominal capacity",
      "Dimensions",
      "Test conditions",
      "Packaging",
    ],
    "Availability and platform specifications are confirmed by quotation. Bespoke electrode matching or cell design belongs to our pouch-cell customization service.",
  ),
  p(
    "eve-lf100la",
    "electrodes-cells",
    "EVE LF100LA prismatic cell",
    "Prismatic battery cell identified by the EVE LF100LA model. Electrical, mechanical and handling parameters must follow the formal specification.",
    ["LF100LA"],
    {
      "Manufacturer designation": "EVE",
      Model: "LF100LA",
      Format: "Prismatic",
    },
    [
      "Manufacturer designation",
      "Model",
      "Format",
      "Nominal capacity",
      "Nominal voltage",
      "Dimensions",
      "Test conditions",
      "Packaging",
    ],
  ),
  p(
    "glass-fiber-1823-047",
    "lab-supplies",
    "Glass-fiber filter media 1823-047",
    "Glass-fiber filter membrane / paper for laboratory workflows. Confirm the exact product designation and filtration requirements.",
    ["1823-047"],
    { Model: "1823-047" },
    [
      "Model",
      "Product designation",
      "Diameter",
      "Retention specification",
      "Thickness",
      "Packaging",
    ],
  ),
  p(
    "nickel-boat",
    "lab-supplies",
    "Nickel boats",
    "Nickel boats for laboratory processing. Share dimensions and intended operating conditions for selection.",
    ["Dimensions to confirm"],
    { Material: "Nickel" },
    [
      "Model",
      "Material",
      "Dimensions",
      "Purity",
      "Operating conditions",
      "Packaging",
    ],
  ),
  p(
    "nickel-boat-lid",
    "lab-supplies",
    "Nickel boat lids",
    "Nickel lids matched to the selected boat geometry.",
    ["Matching lid — dimensions to confirm"],
    { Material: "Nickel" },
    ["Model", "Material", "Dimensions", "Boat compatibility", "Packaging"],
  ),
  p(
    "glass-reactor-2000ml",
    "lab-supplies",
    "2,000 mL glass reaction assembly",
    "Laboratory glass reaction assembly with a specified volume of 2,000 mL. Confirm configuration, connections and operating conditions.",
    ["2,000 mL — configuration to confirm"],
    { Volume: "2,000 mL" },
    [
      "Model",
      "Volume",
      "Glass specification",
      "Connections",
      "Pressure rating",
      "Temperature range",
      "Included components",
    ],
    "No pressure rating is claimed. Confirm suitability before any pressure or vacuum application.",
  ),
  p(
    "emf10",
    "lab-supplies",
    "EMF10 filter cartridge",
    "Filter cartridge supplied by model. Confirm media, connections and compatibility with your system.",
    ["EMF10"],
    { Model: "EMF10" },
    [
      "Model",
      "Filter media",
      "Filtration rating",
      "Dimensions",
      "Connections",
      "Operating conditions",
      "Packaging",
    ],
  ),
  p(
    "un050",
    "lab-supplies",
    "UN050 ultrafiltration membrane",
    "Ultrafiltration membrane supplied by model. Selection requires confirmation of feed compatibility and operating conditions.",
    ["UN050"],
    { Model: "UN050" },
    [
      "Model",
      "Membrane material",
      "Molecular-weight cut-off",
      "Dimensions",
      "Operating conditions",
      "Packaging",
    ],
  ),
  p(
    "copper-sheet",
    "lab-supplies",
    "Laboratory copper sheets",
    "Copper sheets for laboratory and prototype work, selected against your size and material requirements.",
    ["Dimensions / grade to confirm"],
    { Material: "Copper" },
    [
      "Grade",
      "Material",
      "Purity",
      "Thickness",
      "Dimensions",
      "Surface condition",
      "Packaging",
    ],
  ),
  p(
    "check-valve",
    "lab-supplies",
    "Laboratory check valves",
    "Check valves selected for the required medium and laboratory connection format.",
    ["Connection / model to confirm"],
    {},
    [
      "Model",
      "Material",
      "Connection standard",
      "Flow direction",
      "Pressure rating",
      "Medium compatibility",
    ],
  ),
  p(
    "imperial-reducer",
    "lab-supplies",
    "Imperial-size reducing fittings",
    "Reducing fittings for laboratory setups. Thread or tube dimensions and sealing details must be confirmed.",
    ["Size pair / model to confirm"],
    {},
    [
      "Model",
      "Material",
      "Inlet size / standard",
      "Outlet size / standard",
      "Seal type",
      "Pressure rating",
    ],
  ),
  p(
    "adapter-plug",
    "lab-supplies",
    "Adapter plugs",
    "Adapter plugs for laboratory equipment. Provide the source and destination connector formats for matching.",
    ["Connector pair / model to confirm"],
    {},
    [
      "Model",
      "Input connector",
      "Output connector",
      "Electrical rating",
      "Equipment compatibility",
    ],
  ),
  p(
    "chi760f",
    "lab-supplies",
    "CHI760F electrochemical workstation",
    "Electrochemical workstation for laboratory research. Confirm the required measurement configuration and accessories.",
    ["CHI760F"],
    { Model: "CHI760F" },
    [
      "Model",
      "Measurement functions",
      "Current / voltage ranges",
      "Included accessories",
      "Software compatibility",
      "Power requirements",
    ],
  ),
  p(
    "vacuum-sealer",
    "lab-supplies",
    "Vacuum sealing machine",
    "Vacuum sealing equipment selected for the intended packaging and laboratory process.",
    ["Model to confirm"],
    {},
    [
      "Model",
      "Sealing dimensions",
      "Vacuum specification",
      "Compatible packaging",
      "Power requirements",
      "Included accessories",
    ],
  ),
];
const s = (id, name, description, scope, inputs, deliverables, boundary) => ({
  id,
  name,
  description,
  scope,
  inputs,
  deliverables,
  boundary,
});
export const services = [
  s(
    "polymer-resin-synthesis",
    "Polymer & resin synthesis",
    "Synthesis organized around your target structure or SOP.",
    [
      "PEG derivatives, cyclodextrin-related polymers and resin precursors.",
      "Repeat synthesis and agreed batch preparation through partner laboratories and factories.",
    ],
    [
      "Target structure or SOP and permitted process information.",
      "Required quantity, quality criteria and characterization needs.",
    ],
    [
      "Agreed material batch and available characterization records.",
      "Batch documentation and acceptance checks defined in the quotation.",
    ],
    "Route, repeatability and scale are assessed for each project; no blanket purity or yield guarantee.",
  ),
  s(
    "small-molecule-synthesis",
    "Small-molecule & ligand synthesis",
    "Route assessment, synthesis and purification coordination.",
    [
      "Route review, reaction work and separation / purification.",
      "Coordination of agreed characterization.",
    ],
    [
      "Structure, reference route if available, target quantity and purity.",
      "Impurity limits and acceptance methods.",
    ],
    [
      "Agreed compound quantity and characterization package.",
      "Results assessed against the agreed acceptance criteria.",
    ],
    "Purity, yield and acceptance conditions are agreed individually.",
  ),
  s(
    "synthesis-scale-up",
    "Synthesis scale-up & process replication",
    "From laboratory samples to kilogram-scale batches, subject to process review.",
    [
      "Raw-material procurement and SOP replication.",
      "Process iteration and planned batch delivery with partner facilities.",
    ],
    [
      "SOP, reference sample or analytical benchmark.",
      "Target scale, critical process constraints and acceptance criteria.",
    ],
    [
      "Agreed batches and batch records.",
      "Documented process changes and agreed quality checks.",
    ],
    "Scale and schedule depend on route feasibility, safety review and partner capacity.",
  ),
  s(
    "carbonization-activation",
    "Carbonization & activation",
    "Resin carbonization and custom porous-carbon processing.",
    [
      "Resin carbonization and alkali activation.",
      "Steam or CO₂ activation routes assessed against feedstock and partner-facility conditions.",
    ],
    [
      "Feedstock identity, quantity and available safety information.",
      "Target particle size, porosity and analytical requirements.",
    ],
    [
      "Processed carbon samples or agreed batch quantity.",
      "Processing records and characterization as agreed.",
    ],
    "Steam and CO₂ routes are subject to feasibility review, not a standard delivery commitment.",
  ),
  s(
    "sintering-heat-treatment",
    "Scale-up sintering & heat treatment",
    "Kilogram-scale and larger-batch requirements assessed by project.",
    [
      "Review of feedstock, atmosphere, temperature profile and batch handling.",
      "Coordination of suitable partner processing capacity.",
    ],
    [
      "Feedstock specification, batch size and thermal profile.",
      "Atmosphere, contamination limits and acceptance tests.",
    ],
    [
      "An agreed processing plan and, if accepted, processed material.",
      "Available batch records and agreed verification results.",
    ],
    "Subject to project assessment. Cathode sintering and LFP oxidation are evaluated individually for process feasibility, batch size and partner-facility suitability.",
  ),
  s(
    "electrode-processing",
    "Electrode processing",
    "Material sourcing or customer-supplied powders through to cut electrodes.",
    [
      "Slurry and coating coordination, calendaring and cutting.",
      "NFPP, P2, layered-oxide and hard-carbon systems reviewed individually.",
    ],
    [
      "Material specification and formulation / process constraints.",
      "Coating sides, dimensions, areal capacity (mAh/cm²) and mass loading (mg/cm²), stated separately.",
    ],
    [
      "Agreed electrode sheets or cut pieces.",
      "Recorded dimensions and agreed loading / quality checks.",
    ],
    "Formulation, collector, coating window and acceptance criteria are confirmed before processing.",
  ),
  s(
    "pouch-cell-customization",
    "Pouch-cell customization",
    "Electrode matching and cell assembly for a defined research objective.",
    [
      "Cathode / anode matching and stacked-cell assembly.",
      "Dry-cell delivery, or electrolyte filling, formation and capacity grading.",
    ],
    [
      "Chemistry, electrode specifications, geometry and target quantity.",
      "Required delivery state, test protocol and acceptance criteria.",
    ],
    [
      "Agreed dry or filled / formed pouch cells.",
      "Build records and agreed formation or capacity data.",
    ],
    "Wound cells, multi-tab layouts and lithium-metal designs require individual review. Customer performance targets are not measured results or guarantees.",
  ),
  s(
    "battery-testing",
    "Battery testing",
    "Coordinated charge–discharge, cycling, rate and comparative validation.",
    [
      "Test protocol review and test coordination with partner laboratories.",
      "Material characterization coordinated where the project requires it.",
    ],
    [
      "Sample details, safety information and test conditions.",
      "Voltage limits, rates, temperature, sample count and data format.",
    ],
    [
      "Raw data and curves under the agreed protocol.",
      "Comparative summaries or characterization records when included in scope.",
    ],
    "Test outcomes depend on samples and conditions; no cycle-life, rate or energy-density result is promised.",
  ),
  s(
    "research-procurement",
    "Research procurement",
    "Materials, consumables and equipment sourcing for R&D teams.",
    [
      "Material selection, small-batch procurement and equipment sourcing.",
      "Coordination of custom molds, heating mantles and related accessories.",
    ],
    [
      "Specifications, acceptable alternatives and required quantity.",
      "Equipment interfaces, delivery location and desired timing.",
    ],
    [
      "Quoted products or agreed custom accessories.",
      "Available supplier documentation and agreed receiving checks.",
    ],
    "Price, availability, lead time and documentation are confirmed by quotation. No stock or authorized-distributor status is implied.",
  ),
];
