// Curated from the owner's supplied catalog brief. No unverified numeric specs.
export const categories = [
  {
    id: "battery-materials",
    name: "Battery materials",
    description:
      "Hard carbon, porous carbon, CVD silicon–carbon and NFPP powders for electrode research.",
  },
  {
    id: "binders-electrolytes",
    name: "Binders & electrolytes",
    description:
      "Model-specific binders and electrolytes for battery development.",
  },
  {
    id: "electrodes-cells",
    name: "Electrodes & cells",
    description:
      "NFPP and P2 electrodes, research pouch cells and prismatic cells.",
  },
  {
    id: "lab-supplies",
    name: "Lab supplies & equipment",
    description:
      "Filtration media, reactor glassware, accessories and electrochemical equipment.",
  },
];
const powderFields = [
  "Grade",
  "Feedstock type",
  "Particle size",
  "BET surface area",
  "Pore volume",
  "Specific capacity",
  "Initial coulombic efficiency",
  "Test conditions",
  "Packaging",
];
const p = (
  id,
  category,
  name,
  description,
  models,
  specs,
  fields,
  note = "",
) => ({
  id,
  category,
  name,
  description,
  models,
  specs,
  missingSpecs: fields.filter((key) => !Object.hasOwn(specs, key)),
  note,
});
export const products = [
  p(
    "resin-derived-hard-carbon",
    "battery-materials",
    "Resin-Derived Hard Carbon",
    "Resin-derived hard carbon for sodium-ion battery anode research.",
    [],
    { "Feedstock type": "Resin-derived", Application: "Sodium-ion battery anode research" },
    powderFields,
  ),
  p(
    "biomass-derived-hard-carbon",
    "battery-materials",
    "Biomass-Derived Hard Carbon",
    "Biomass-derived hard carbon for sodium-ion battery anode research.",
    [],
    { "Feedstock type": "Biomass-derived", Application: "Sodium-ion battery anode research" },
    powderFields,
  ),
  p(
    "spherical-porous-carbon",
    "battery-materials",
    "Spherical porous carbon",
    "Porous carbon for silicon–carbon anode research and as a host for silicon deposition.",
    [
      "Alkali-activated",
      "Water-activated",
    ],
    {
      "Activation type":
        "Alkali-activated or water-activated",
    },
    [...powderFields, "Activation type"],
  ),
  p(
    "cvd-silicon-carbon",
    "battery-materials",
    "CVD silicon–carbon anode powder",
    "Silicon–carbon powder for anode research, including spherical material with a secondary carbon coating.",
    ["Spherical, secondary carbon coating"],
    {
      "Morphology / coating":
        "Spherical; secondary carbon coating",
    },
    [...powderFields, "Morphology / coating"],
  ),
  p(
    "nfpp-powder",
    "battery-materials",
    "NFPP cathode powder",
    "NFPP powder for sodium-ion research and electrode processing, including a rate-oriented material option.",
    ["NFPP", "Rate-oriented NFPP"],
    { "Material": "NFPP" },
    powderFields,
    "Rate capability depends on the selected grade and agreed test conditions; no performance value is specified.",
  ),
  p(
    "al-3001a",
    "binders-electrolytes",
    "A&L AL-3001A SBR binder",
    "SBR binder for negative-electrode development.",
    ["AL-3001A"],
    {
      Model: "AL-3001A",
      "Supplier designation": "A&L",
      Application: "Negative-electrode binder",
    },
    [
      "Model",
      "Supplier designation",
      "Application",
      "Solids content",
      "Packaging",
      "Storage conditions",
    ],
  ),
  p(
    "jone-174",
    "binders-electrolytes",
    "JONE-174 battery binder",
    "Battery binder supplied as JONE-174.",
    ["JONE-174"],
    { Model: "JONE-174" },
    [
      "Model",
      "Formal product name",
      "Compatible chemistry",
      "Solids content",
      "Packaging",
      "Storage conditions",
    ],
  ),
  ...["QMS029D", "XYSS-DGHYKJ118"].map((model) =>
    p(
      model.toLowerCase(),
      "binders-electrolytes",
      `${model} electrolyte`,
      "Battery research electrolyte supplied by model.",
      [model],
      { Model: model },
      [
        "Model",
        "Compatible chemistry",
        "Composition",
        "Voltage limit",
        "Packaging",
        "Storage conditions",
      ],
    ),
  ),
  p(
    "nfm-electrolyte",
    "binders-electrolytes",
    "Electrolyte for NFM sodium-ion systems",
    "Electrolyte for NFM sodium-ion development.",
    ["NFM-compatible"],
    { Application: "NFM sodium-ion development" },
    [
      "Model",
      "Application",
      "Composition",
      "Voltage limit",
      "Packaging",
      "Storage conditions",
    ],
  ),
  p(
    "nfpp-electrode",
    "electrodes-cells",
    "NFPP cathode electrodes",
    "NFPP cathode electrodes for sodium-ion experiments.",
    ["Single-sided", "Double-sided"],
    { "Active material": "NFPP" },
    [
      "Model",
      "Active material",
      "Coating sides",
      "Dimensions",
      "Areal capacity (mAh/cm²)",
      "Mass loading (mg/cm²)",
      "Current collector",
      "Packaging",
    ],
  ),
  p(
    "p2-electrode",
    "electrodes-cells",
    "P2 sodium-ion cathode electrodes",
    "P2 cathode electrodes for sodium-ion research, including a double-sided cut-sheet option.",
    ["7.5 × 5.4 cm, double-sided"],
    { Dimensions: "7.5 × 5.4 cm", "Coating sides": "Double-sided" },
    [
      "Model",
      "Dimensions",
      "Coating sides",
      "Areal capacity (mAh/cm²)",
      "Mass loading (mg/cm²)",
      "Current collector",
      "Packaging",
    ],
    "Areal capacity and mass loading are separate quantities; one-sided and two-sided values use different bases.",
  ),
  p(
    "research-pouch-cells",
    "electrodes-cells",
    "Research pouch cells",
    "Existing sodium-ion and lithium-ion platforms for R&D. Select dry cells or electrolyte-filled, formed cells; platform suitability is reviewed with your requirements.",
    [
      "Sodium-ion — dry cell",
      "Sodium-ion — filled and formed",
      "Lithium-ion — dry cell",
      "Lithium-ion — filled and formed",
    ],
    {},
    [
      "Platform / model",
      "Electrode chemistry",
      "Delivery state",
      "Nominal capacity",
      "Dimensions",
      "Test conditions",
      "Packaging",
    ],
    "Bespoke electrode matching or cell design is available through our pouch-cell customization service.",
  ),
  p(
    "eve-lf100la",
    "electrodes-cells",
    "EVE LF100LA prismatic cell",
    "Prismatic battery cell identified by the EVE LF100LA model. Electrical, mechanical and handling parameters must follow the formal specification.",
    ["LF100LA"],
    {
      "Manufacturer designation": "EVE",
      Model: "LF100LA",
      Format: "Prismatic",
    },
    [
      "Manufacturer designation",
      "Model",
      "Format",
      "Nominal capacity",
      "Nominal voltage",
      "Dimensions",
      "Test conditions",
      "Packaging",
    ],
  ),
  p(
    "glass-fiber-1823-047",
    "lab-supplies",
    "Glass-fiber filter media 1823-047",
    "Glass-fiber filter membrane / paper for laboratory workflows.",
    ["1823-047"],
    { Model: "1823-047" },
    [
      "Model",
      "Product designation",
      "Diameter",
      "Retention specification",
      "Thickness",
      "Packaging",
    ],
  ),
  p(
    "nickel-boat",
    "lab-supplies",
    "Nickel boats",
    "Nickel boats for laboratory processing. Share dimensions and intended operating conditions for selection.",
    [],
    { Material: "Nickel" },
    [
      "Model",
      "Material",
      "Dimensions",
      "Purity",
      "Operating conditions",
      "Packaging",
    ],
  ),
  p(
    "nickel-boat-lid",
    "lab-supplies",
    "Nickel boat lids",
    "Nickel lids matched to the selected boat geometry.",
    ["Matching lid"],
    { Material: "Nickel" },
    ["Model", "Material", "Dimensions", "Boat compatibility", "Packaging"],
  ),
  p(
    "glass-reactor-2000ml",
    "lab-supplies",
    "2,000 mL glass reaction assembly",
    "Laboratory glass reaction assembly with a volume of 2,000 mL.",
    ["2,000 mL"],
    { Volume: "2,000 mL" },
    [
      "Model",
      "Volume",
      "Glass specification",
      "Connections",
      "Pressure rating",
      "Temperature range",
      "Included components",
    ],
    "No pressure rating is claimed. Confirm suitability before any pressure or vacuum application.",
  ),
  p(
    "emf10",
    "lab-supplies",
    "EMF10 filter cartridge",
    "EMF10 filter cartridge.",
    ["EMF10"],
    { Model: "EMF10" },
    [
      "Model",
      "Filter media",
      "Filtration rating",
      "Dimensions",
      "Connections",
      "Operating conditions",
      "Packaging",
    ],
  ),
  p(
    "un050",
    "lab-supplies",
    "UN050 ultrafiltration membrane",
    "UN050 ultrafiltration membrane.",
    ["UN050"],
    { Model: "UN050" },
    [
      "Model",
      "Membrane material",
      "Molecular-weight cut-off",
      "Dimensions",
      "Operating conditions",
      "Packaging",
    ],
  ),
  p(
    "copper-sheet",
    "lab-supplies",
    "Laboratory copper sheets",
    "Copper sheets for laboratory and prototype work, selected against your size and material requirements.",
    [],
    { Material: "Copper" },
    [
      "Grade",
      "Material",
      "Purity",
      "Thickness",
      "Dimensions",
      "Surface condition",
      "Packaging",
    ],
  ),
  p(
    "check-valve",
    "lab-supplies",
    "Laboratory check valves",
    "Check valves selected for the required medium and laboratory connection format.",
    [],
    {},
    [
      "Model",
      "Material",
      "Connection standard",
      "Flow direction",
      "Pressure rating",
      "Medium compatibility",
    ],
  ),
  p(
    "imperial-reducer",
    "lab-supplies",
    "Imperial-size reducing fittings",
    "Reducing fittings for laboratory setups.",
    [],
    {},
    [
      "Model",
      "Material",
      "Inlet size / standard",
      "Outlet size / standard",
      "Seal type",
      "Pressure rating",
    ],
  ),
  p(
    "adapter-plug",
    "lab-supplies",
    "Adapter plugs",
    "Adapter plugs for laboratory equipment. Provide the source and destination connector formats for matching.",
    [],
    {},
    [
      "Model",
      "Input connector",
      "Output connector",
      "Electrical rating",
      "Equipment compatibility",
    ],
  ),
  p(
    "chi760f",
    "lab-supplies",
    "CHI760F electrochemical workstation",
    "Electrochemical workstation for laboratory research.",
    ["CHI760F"],
    { Model: "CHI760F" },
    [
      "Model",
      "Measurement functions",
      "Current / voltage ranges",
      "Included accessories",
      "Software compatibility",
      "Power requirements",
    ],
  ),
  p(
    "vacuum-sealer",
    "lab-supplies",
    "Vacuum sealing machine",
    "Vacuum sealing equipment selected for the intended packaging and laboratory process.",
    [],
    {},
    [
      "Model",
      "Sealing dimensions",
      "Vacuum specification",
      "Compatible packaging",
      "Power requirements",
      "Included accessories",
    ],
  ),
];
const s = (id, name, description, scope, inputs, deliverables, boundary) => ({
  id,
  name,
  description,
  scope,
  inputs,
  deliverables,
  boundary,
});
export const services = [
  s(
    "material-characterization",
    "Material characterization",
    "Connect your material development with specialist characterization resources, including SEM and TEM, to understand structure and morphology as you validate samples and scale your process.",
    ["SEM and TEM imaging to examine surface morphology and microstructure, subject to sample and method assessment.", "Review of the material, characterization objective and suitable test methods.", "Coordination of the agreed measurements and reporting scope."],
    ["Sample composition, form, quantity, handling and safety information.", "Characterization objectives, requested methods, reference data and acceptance criteria."],
    ["Agreed characterization results and available raw data.", "Method and test-condition information within the agreed reporting scope."],
    "Methods, sample requirements, data format and interpretation scope are assessed for each project. No specific instrument availability or accreditation is implied.",
  ),
  s(
    "functional-materials-development",
    "Functional materials development",
    "We connect synthesis expertise, equipment and characterization resources to advance MOFs, COFs and functional materials from milligram-scale discovery toward gram- and kilogram-scale development.",
    [
      "Route assessment and synthesis coordination for metal–organic frameworks (MOFs) and covalent organic frameworks (COFs).",
      "Functional polymers, resins, ligands and related intermediates; process reproduction or optimization when agreed.",
      "Coordination of purification, agreed characterization and project-specific material preparation.",
    ],
    [
      "Target structure or composition, intended function and required quantity.",
      "Approved procedure or literature references, prior results where available, and confidentiality requirements.",
      "Material form, packaging, timeline, test methods, reference data and acceptable tolerances.",
    ],
    [
      "Material batches and characterization results defined in the agreed scope.",
      "Acceptance against procedure compliance, material specifications, or both, as agreed before starting.",
    ],
    "Each framework and route requires feasibility review. Quantity, iteration limits and terms for unmet targets are agreed in advance. Specific structure, porosity, purity, performance or scale-up outcomes are not blanket guarantees.",
  ),
  s(
    "polymer-resin-synthesis",
    "Polymer & resin synthesis",
    "We bring together specialist synthesis facilities and process experience to advance your polymer or resin from milligram-scale lab work to gram- and kilogram-scale development, with characterization alongside scale-up.",
    [
      "PEG derivatives, cyclodextrin-related polymers and resin precursors.",
      "Repeat synthesis and agreed batch preparation through partner laboratories and factories.",
    ],
    [
      "Target structure or SOP and permitted process information.",
      "Required quantity, quality criteria and characterization needs.",
    ],
    [
      "Agreed material batch and available characterization records.",
      "Batch documentation and acceptance checks defined in the quotation.",
    ],
    "Route, repeatability and scale are assessed for each project; no blanket purity or yield guarantee.",
  ),
  s(
    "small-molecule-synthesis",
    "Small-molecule & ligand synthesis",
    "We connect synthesis, purification and analytical expertise to accelerate the development of your target molecules and ligands, from milligram-scale experiments toward gram- and kilogram-scale batches.",
    [
      "Route review, reaction work and separation / purification.",
      "Coordination of agreed characterization.",
    ],
    [
      "Structure, reference route if available, target quantity and purity.",
      "Impurity limits and acceptance methods.",
    ],
    [
      "Agreed compound quantity and characterization package.",
      "Results assessed against the agreed acceptance criteria.",
    ],
    "Purity, yield and acceptance conditions are agreed individually.",
  ),
  s(
    "synthesis-scale-up",
    "Synthesis scale-up & process replication",
    "We connect your lab-scale material or catalyst synthesis with partner equipment and process expertise to develop repeatable gram- and kilogram-scale processes and validate the material as scale increases.",
    [
      "Raw-material procurement and SOP replication.",
      "Process iteration and planned batch delivery with partner facilities.",
    ],
    [
      "SOP, reference sample or analytical benchmark.",
      "Target scale, critical process constraints and acceptance criteria.",
    ],
    [
      "Agreed batches and batch records.",
      "Documented process changes and agreed quality checks.",
    ],
    "Scale and schedule depend on route feasibility, safety review and partner capacity.",
  ),
  s(
    "carbonization-activation",
    "Carbonization & activation",
    "We connect your lab-scale carbon work with larger furnaces, activation equipment and processing experience to develop larger batches and validate the resulting carbon structure and properties.",
    [
      "Resin carbonization and alkali activation.",
      "Steam or CO₂ activation routes assessed against feedstock and partner-facility conditions.",
    ],
    [
      "Feedstock identity, quantity and available safety information.",
      "Target particle size, porosity and analytical requirements.",
    ],
    [
      "Processed carbon samples or agreed batch quantity.",
      "Processing records and characterization as agreed.",
    ],
    "Steam and CO₂ routes are subject to feasibility review, not a standard delivery commitment.",
  ),
  s(
    "sintering-heat-treatment",
    "Scale-up sintering & heat treatment",
    "We match your material and thermal process with suitable partner furnaces and process expertise to evaluate kilogram-scale sintering and heat treatment beyond the laboratory.",
    [
      "Review of feedstock, atmosphere, temperature profile and batch handling.",
      "Coordination of suitable partner processing capacity.",
    ],
    [
      "Feedstock specification, batch size and thermal profile.",
      "Atmosphere, contamination limits and acceptance tests.",
    ],
    [
      "An agreed processing plan and, if accepted, processed material.",
      "Available batch records and agreed verification results.",
    ],
    "Subject to project assessment. Cathode sintering and LFP oxidation are evaluated individually for process feasibility, batch size and partner-facility suitability.",
  ),
  s(
    "electrode-processing",
    "Electrode processing",
    "We connect your materials with slurry, roll-to-roll coating and finishing expertise to advance lab electrodes toward square-metre and larger pilot coating trials, validating uniformity and performance as scale increases.",
    [
      "Slurry and coating coordination, calendaring and cutting.",
      "NFPP, P2, layered-oxide and hard-carbon systems reviewed individually.",
    ],
    [
      "Material specification and formulation / process constraints.",
      "Coating sides, dimensions, areal capacity (mAh/cm²) and mass loading (mg/cm²), stated separately.",
    ],
    [
      "Agreed electrode sheets or cut pieces.",
      "Recorded dimensions and agreed loading / quality checks.",
    ],
    "Formulation, collector, coating window and acceptance criteria are confirmed before processing.",
  ),
  s(
    "pouch-cell-customization",
    "Pouch-cell customization",
    "We connect electrode processing, cell assembly and testing expertise to advance your coin-cell results into pouch-cell prototypes and validate the technology before the next step toward pack-level development.",
    [
      "Cathode / anode matching and stacked-cell assembly.",
      "Dry-cell delivery, or electrolyte filling, formation and capacity grading.",
    ],
    [
      "Chemistry, electrode specifications, geometry and target quantity.",
      "Required delivery state, test protocol and acceptance criteria.",
    ],
    [
      "Agreed dry or filled / formed pouch cells.",
      "Build records and agreed formation or capacity data.",
    ],
    "Wound cells, multi-tab layouts and lithium-metal designs require individual review. Customer performance targets are not measured results or guarantees.",
  ),
  s(
    "battery-testing",
    "Battery testing",
    "We connect lithium-ion, solid-state and pouch-cell development with cycling, rate and comparative testing to validate performance as your technology moves into larger cell formats.",
    [
      "Lithium-ion, solid-state and pouch cell testing, with fixtures and safety requirements reviewed for each cell format.",
      "Test protocol review and test coordination with partner laboratories.",
      "Material characterization coordinated where the project requires it.",
    ],
    [
      "Sample details, safety information and test conditions.",
      "Voltage limits, rates, temperature, sample count and data format.",
    ],
    [
      "Raw data and curves under the agreed protocol.",
      "Comparative summaries or characterization records when included in scope.",
    ],
    "Test outcomes depend on samples and conditions; no cycle-life, rate or energy-density result is promised.",
  ),
  s(
    "stack-testing", "Fuel-cell & electrolyzer stack testing",
    "We connect fuel-cell and electrolyzer development with suitable short-stack and full-stack test facilities to evaluate performance as you move from individual cells to larger systems.",
    ["Review of stack configuration, interfaces and operating envelope.", "Agreed performance, operating stability and system-level validation protocols."],
    ["Stack chemistry, cell count, dimensions and electrical / fluid interfaces.", "Operating conditions, safety documentation, test objectives and reporting needs."],
    ["Agreed test records, raw data and performance curves.", "Test configuration and operating-condition summary."],
    "Facility compatibility, stack size, power range, gas handling and test scope require project assessment. No fixed capacity or accredited method is implied.",
  ),
  s(
    "renewable-coupled-testing", "Wind & solar direct-coupling tests",
    "We bring together electrolysis and power-system expertise to assess wind and solar coupling and validate operation under variable renewable power, matching the test setup to your technology.",
    ["Review of the proposed power source, electrical interfaces and electrolysis configuration.", "Coordination of variable-power operation and direct-coupling validation where facilities and interfaces are compatible."],
    ["Electrical architecture, power profiles, control strategy and electrolyzer specifications.", "Safety requirements, validation criteria and requested data."],
    ["Agreed operating data and test-condition records.", "Observations against the agreed validation objectives."],
    "Direct connection, actual renewable sources versus reproduced power profiles, available facilities and safety controls are confirmed per project; no ready-to-use test site or output guarantee is implied.",
  ),
  s(
    "research-procurement",
    "Research procurement",
    "We connect your research team with materials, equipment and specialist suppliers so you can move from lab experiments to larger-scale development with the right technical resources.",
    [
      "Material selection, small-batch procurement and equipment sourcing.",
      "Coordination of custom molds, heating mantles and related accessories.",
    ],
    [
      "Specifications, acceptable alternatives and required quantity.",
      "Equipment interfaces, delivery location and desired timing.",
    ],
    [
      "Quoted products or agreed custom accessories.",
      "Available supplier documentation and agreed receiving checks.",
    ],
    "Price, availability, lead time and documentation are confirmed by quotation. No stock or authorized-distributor status is implied.",
  ),
];
